### ISSUE TITLE
US01 - Postagem Anonima 

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2020.1-VC_Usuario#104]
### Descrição:
Eu, como **usuário**, desejo **realizar** uma **postagem anônima**

### Tarefas:
- Criar uma model para a postagem e para o usuário: @DanielPortods e @daniel-bm;
- Definir uma rota para a postagem e testar no back se a postagem foi criada: @emysdias e @enzoggqs 
- Criar a tela de criar a postagem e fazer a mesma pegar a rota para a postagem:  @Bruno-Felix @DenysRogeres

### Critérios de aceitação:

--- 

#### Identidade Visual: #66

**Comment by Bruno-Felix** [comment]
#### Criar a tela de criar a postagem e fazer a mesma consumir a API do back end: 
- @Bruno-Felix @DenysRogeres;
- [x] Criar componente Header;
- [x] Criar componente MenuBar;
- [x] Desenvolver comportamento do componente Header no scroll;
- [ ] Inserir imagem na Header;
- [x] Criar página Criar Postagem;
- [ ] Desenvolver página Criar Postagem;
- [ ] Consumir a API e retornar a postagem criada.
