### ISSUE TITLE
Revisar Roadmap

### ISSUE THREAD

**Issue by enzoggqs** [fga-eps-mds/2020.1-VC_Usuario#86]
### Descrição:

Ver roadmaps de grupos anteriores e fazer revisão no roadmap do projeto.

### Tarefas:

- [ ] Olhar roadmap de grupos anteriores;
- [ ] Fazer revisão do roadmap do projeto.

### Critérios de aceitação:

- [ ] Revisão do roadmap e acréscimo de elementos se necessário.
